DATABASE_URL = "45.32.224.205"
DATABASE_USERNAME = "dxr"
DATABASE_PASSWORD = "dxr"
DATABASE_NAME = "network_asset"
RAW_POC_LIST = "https://raw.githubusercontent.com/boy-hack/airbug/master/API.json"
RAW_POC_LIST_KEYS = ["name", "type", "filepath", "time"]
POC_INFO_TABLE_NAME = "poc_info"
POC_INFO_TABLE_FIELDS = ["id", "name", "type", "file_path", "create_time", "url"]
POC_SCRIPT_FOLDER_NAME = "poc_script"
RAW_POC_SCRIPT_ROOT_PATH = "https://raw.githubusercontent.com/boy-hack/airbug/master"
